
all: main

main: main.swift font.swift
	swiftc -I../COpenGL -I../CFreeGLUT -I/home/bay/tmp/614_swift/build/Ninja-ReleaseAssert/foundation-linux-x86_64/Foundation/usr/lib/swift -I/home/bay/tmp/614_swift/build/Ninja-ReleaseAssert/foundation-linux-x86_64/Foundation -L/home/bay/tmp/614_swift/build/Ninja-ReleaseAssert/foundation-linux-x86_64/Foundation main.swift font.swift

clean:
	rm main